# Generated by Django 4.1.1 on 2022-09-26 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_remove_company_inceptiondate2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                ("teamId", models.UUIDField(primary_key=True, serialize=False)),
                ("teamLeadName", models.CharField(max_length=50)),
                (
                    "companyId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
        ),
    ]
