# Generated by Django 4.1.1 on 2022-09-26 08:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="companyId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="teams",
            name="teamId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
